### PR TITLE
Update for >= 11.226x1.2050

### PR DESCRIPTION
**Pull request by y2nd66**

### CODE REVIEW

**Comment by dankrusi** [comment]
Hi @y2nd66,

Great - thanks. Quick question: how reliable is the REG key SOFTWARE\Microsoft\Windows NT\CurrentVersion\UBR? In other words, will the code crash if build >= 22621 but no such reg key?

Best,

-dan

**Comment by y2nd66** [comment]
Hi @dankrusi 

I don't know how reliable that entry would be

function **GetWindowsBuildVersion** uses the same registry entry
[here](https://i.imgur.com/TBvFcIq.png)

UBR key is what **winver.exe** is looking for as the build number
[here](https://i.imgur.com/9wnpHIL.png)

as far as I know Microsoft does not have documented

excuse my English
Best,
ygg

**Comment by dankrusi** [comment]
@y2nd66  thanks!

**Comment by dankrusi** [comment]
Hi @y2nd66, would you mind debugging the switch desktop feature in your implementation - some users are having an issue with it. I don't think its the GUID of the API. Unfortunately I am having trouble installing this exact version of Windows... Thanks!

App.Instance.VDAPI.SwitchBackward();
App.Instance.VDAPI.SwitchForward();

**Pull request merged**
