### PR TITLE
Grab focus of the last focused window automatically when switching

### PR DESCRIPTION
**Pull request by MadoScientist97**
Had been using it for a few months now and the fact that it doesn't automatically focuses when switching between the desktops was a huge pita, with me having to constantly hit alt+tab.

Main features added:
The changes here, fixes that, by associating the last focused window to its virtual desktop number and refocusing on that window when coming back to that desktop.

Changes:
- changed the VirtualDesktopManager interface to query for the number of VDesktops.
- Refactored for the same in all the implementing classes (more testing needed)
- Added a few win32 methods to query and set focus of the windows
- Added a Dictionary to associate the last focused window on a desktop
- Added utility methods to store and restore the focus state.

Additionally Incorporates changes suggested in this PR as well: https://github.com/dankrusi/WindowsVirtualDesktopHelper/pull/136

### CODE REVIEW

**Comment by dankrusi** [comment]
hi @MadoScientist97, great work many thanks! Quick question: you didn't add any new undocumented Windows API calls right? For the total desktop count you use the already existing VirtualDesktopManagerInternal.GetCount()  - so we don't need to retest all the variations of Win11 and Win10 API CLIDs... Just making sure we don't break anything. Also, the win32 methods you added work for Win10 and Win11 and all variations?

**Comment by MadoScientist97** [comment]
Closes https://github.com/dankrusi/WindowsVirtualDesktopHelper/issues/151

**Comment by MadoScientist97** [comment]
@dankrusi FYI

**Comment by ashish-bhardwaj-git** [comment]
I'm experiencing an occasional glitch with the virtual desktop hotkeys. While the focus issue is resolved, [for example] sometimes hitting the hotkey for Desktop 4 sends me to Desktop 2 first. A second press then correctly switches me to Desktop 4. It's not constant, but it's happening fairly frequently, also it's crashing a lot ;(

**Comment by MadoScientist97** [comment]
Thanks for reporting, which build/version of windows are you using also please attach any logs. @ashish-bhardwaj-git

**Comment by ashish-bhardwaj-git** [comment]
Hey I'm currently using windows [23H2], I've built it again the crashing part is resolved but , desktop switching problem is still there.

**Comment by ashish-bhardwaj-git** [comment]
Hey I'm currently using windows 11 [23H2], I've built it again the crashing part is resolved but , desktop switching problem is still there.

**Comment by ashish-bhardwaj-git** [comment]
@MadoScientist97 Thanks the issue with Switching desktops is resolved but, the  focus part was working perfectly in you previous build, previously it remembered the window of a desktop now i have to press alt + tab or click on the window. [this was originally the issue].

**Comment by ashish-bhardwaj-git** [comment]
> I'm experiencing an occasional glitch with the virtual desktop hotkeys. While the focus issue is resolved, [for example] sometimes hitting the hotkey for Desktop 4 sends me to Desktop 2 first. A second press then correctly switches me to Desktop 4. It's not constant, but it's happening fairly frequently, also it's crashing a lot ;(

it's still there unfortunately

**Comment by MadoScientist97** [comment]
Hi @MadoScientist97 was really busy with my job, I had actually forgot about this, I am getting back it this weekend. Lemme see what I can do. Trying to find if there is a os provided way to do it async on a desktop change event, not sure how well it will fit tho.

**Comment by ashish-bhardwaj-git** [comment]
> Hi @ashish-bhardwaj-git was really busy with my job, I had actually forgot about this, I am getting back it this weekend. Lemme see what I can do. Trying to find if there is a os provided way to do it async on a desktop change event, not sure how well it will fit tho.

Thanks for giving your time <3

**Pull request merged**
